### ISSUE TITLE
WIngTipToys porting related changes to be done

### ISSUE THREAD

**Issue by birojnayak** [CoreWebForms/CoreWebForms#190]
Tracking various tasks
- [ ] Fixing Authentication https://github.com/CoreWebForms/Samples/issues/10
- [ ] Fixing Owin support https://github.com/CoreWebForms/Samples/issues/11
- [ ] Port friendly Urls or find alternative in Core https://github.com/CoreWebForms/CoreWebForms/issues/16
- [ ] Port user control https://github.com/CoreWebForms/CoreWebForms/issues/19
- [ ] Port validation summary https://github.com/CoreWebForms/CoreWebForms/issues/189
- [ ] Fix the category filter
