### ISSUE TITLE
Tracking work related to Sitemap and Menucontrols

### ISSUE THREAD

**Issue by birojnayak** [CoreWebForms/CoreWebForms#266]
Tracking various tasks
- [ ] Getting basic controls as below as per #261 with default XMLProvider
    System.Web.UI.WebControls.Menu
    System.Web.UI.WebControls.MenuItem
    System.Web.UI.WebControls.MenuItemCollection
    System.Web.UI.WebControls.MenuAdapter
    System.Web.UI.WebControls.CompareValidator

- [ ] Get Web.Config (system.web/sitemap) support
- [ ] Handle providers init better
- [ ] Fix test cases to handle view state
- [ ] Add tests coverage for subfolders and sitemap
- [ ] Change VirtualPathProvider OpenFile to use Adapter openfile

**Comment by twsouthwick** [comment]
Do we need the XML Provider?

**Comment by birojnayak** [comment]
> Do we need the XML Provider? What is required for minimal support?

@twsouthwick https://github.com/CoreWebForms/CoreWebForms/pull/265 takes care the first requirement. We are getting src/WebForms/XmlSiteMapProvider.cs part of the first PR. Once this is merged I will put a tick mark.
